// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq33iNlLjcuvfPi6haIP5WUx4lVD9vAP0',
    appId: '1:972994587449:web:14e74abd759c0d6abb16e8',
    messagingSenderId: '972994587449',
    projectId: 'habitat-dd4b2',
    authDomain: 'habitat-dd4b2.firebaseapp.com',
    storageBucket: 'habitat-dd4b2.appspot.com',
    measurementId: 'G-TQXKH6YDHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLmbXCn57Pm9w9EE5p2S2ZozbF_jg0JFE',
    appId: '1:972994587449:android:b4d3b37e3ad8d719bb16e8',
    messagingSenderId: '972994587449',
    projectId: 'habitat-dd4b2',
    storageBucket: 'habitat-dd4b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOU5iNhWiHg73ZSmVOLuGsvL49u6EXjbs',
    appId: '1:972994587449:ios:0d0dcc7fa55bc07fbb16e8',
    messagingSenderId: '972994587449',
    projectId: 'habitat-dd4b2',
    storageBucket: 'habitat-dd4b2.appspot.com',
    iosBundleId: 'com.example.habitatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOU5iNhWiHg73ZSmVOLuGsvL49u6EXjbs',
    appId: '1:972994587449:ios:0d0dcc7fa55bc07fbb16e8',
    messagingSenderId: '972994587449',
    projectId: 'habitat-dd4b2',
    storageBucket: 'habitat-dd4b2.appspot.com',
    iosBundleId: 'com.example.habitatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq33iNlLjcuvfPi6haIP5WUx4lVD9vAP0',
    appId: '1:972994587449:web:2c7a9b0e14465246bb16e8',
    messagingSenderId: '972994587449',
    projectId: 'habitat-dd4b2',
    authDomain: 'habitat-dd4b2.firebaseapp.com',
    storageBucket: 'habitat-dd4b2.appspot.com',
    measurementId: 'G-E31495KBWY',
  );
}
